dist: trusty
language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-10

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake .
  - cmake --build . -- -j2
  - ctest -j2
